// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: rand_quote.proto

package randquotev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RandQuotes_GetQuote_FullMethodName                   = "/github.com.mashmorsik.rand.quote.grpc.v1.RandQuotes/GetQuote"
	RandQuotes_ListQuotes_FullMethodName                 = "/github.com.mashmorsik.rand.quote.grpc.v1.RandQuotes/ListQuotes"
	RandQuotes_GetSeveralCharactersQuotes_FullMethodName = "/github.com.mashmorsik.rand.quote.grpc.v1.RandQuotes/GetSeveralCharactersQuotes"
	RandQuotes_QuotesChat_FullMethodName                 = "/github.com.mashmorsik.rand.quote.grpc.v1.RandQuotes/QuotesChat"
)

// RandQuotesClient is the client API for RandQuotes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RandQuotesClient interface {
	GetQuote(ctx context.Context, in *RandQuoteRequest, opts ...grpc.CallOption) (*RandQuoteResponse, error)
	ListQuotes(ctx context.Context, in *ListQuotesRequest, opts ...grpc.CallOption) (RandQuotes_ListQuotesClient, error)
	GetSeveralCharactersQuotes(ctx context.Context, opts ...grpc.CallOption) (RandQuotes_GetSeveralCharactersQuotesClient, error)
	QuotesChat(ctx context.Context, opts ...grpc.CallOption) (RandQuotes_QuotesChatClient, error)
}

type randQuotesClient struct {
	cc grpc.ClientConnInterface
}

func NewRandQuotesClient(cc grpc.ClientConnInterface) RandQuotesClient {
	return &randQuotesClient{cc}
}

func (c *randQuotesClient) GetQuote(ctx context.Context, in *RandQuoteRequest, opts ...grpc.CallOption) (*RandQuoteResponse, error) {
	out := new(RandQuoteResponse)
	err := c.cc.Invoke(ctx, RandQuotes_GetQuote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *randQuotesClient) ListQuotes(ctx context.Context, in *ListQuotesRequest, opts ...grpc.CallOption) (RandQuotes_ListQuotesClient, error) {
	stream, err := c.cc.NewStream(ctx, &RandQuotes_ServiceDesc.Streams[0], RandQuotes_ListQuotes_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &randQuotesListQuotesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RandQuotes_ListQuotesClient interface {
	Recv() (*ListQuotesResponse, error)
	grpc.ClientStream
}

type randQuotesListQuotesClient struct {
	grpc.ClientStream
}

func (x *randQuotesListQuotesClient) Recv() (*ListQuotesResponse, error) {
	m := new(ListQuotesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *randQuotesClient) GetSeveralCharactersQuotes(ctx context.Context, opts ...grpc.CallOption) (RandQuotes_GetSeveralCharactersQuotesClient, error) {
	stream, err := c.cc.NewStream(ctx, &RandQuotes_ServiceDesc.Streams[1], RandQuotes_GetSeveralCharactersQuotes_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &randQuotesGetSeveralCharactersQuotesClient{stream}
	return x, nil
}

type RandQuotes_GetSeveralCharactersQuotesClient interface {
	Send(*SeveralCharactersQuotesRequest) error
	CloseAndRecv() (*SeveralCharacterQuotesResponse, error)
	grpc.ClientStream
}

type randQuotesGetSeveralCharactersQuotesClient struct {
	grpc.ClientStream
}

func (x *randQuotesGetSeveralCharactersQuotesClient) Send(m *SeveralCharactersQuotesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *randQuotesGetSeveralCharactersQuotesClient) CloseAndRecv() (*SeveralCharacterQuotesResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SeveralCharacterQuotesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *randQuotesClient) QuotesChat(ctx context.Context, opts ...grpc.CallOption) (RandQuotes_QuotesChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &RandQuotes_ServiceDesc.Streams[2], RandQuotes_QuotesChat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &randQuotesQuotesChatClient{stream}
	return x, nil
}

type RandQuotes_QuotesChatClient interface {
	Send(*QuotesChatRequest) error
	Recv() (*QuotesChatResponse, error)
	grpc.ClientStream
}

type randQuotesQuotesChatClient struct {
	grpc.ClientStream
}

func (x *randQuotesQuotesChatClient) Send(m *QuotesChatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *randQuotesQuotesChatClient) Recv() (*QuotesChatResponse, error) {
	m := new(QuotesChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RandQuotesServer is the server API for RandQuotes service.
// All implementations must embed UnimplementedRandQuotesServer
// for forward compatibility
type RandQuotesServer interface {
	GetQuote(context.Context, *RandQuoteRequest) (*RandQuoteResponse, error)
	ListQuotes(*ListQuotesRequest, RandQuotes_ListQuotesServer) error
	GetSeveralCharactersQuotes(RandQuotes_GetSeveralCharactersQuotesServer) error
	QuotesChat(RandQuotes_QuotesChatServer) error
	mustEmbedUnimplementedRandQuotesServer()
}

// UnimplementedRandQuotesServer must be embedded to have forward compatible implementations.
type UnimplementedRandQuotesServer struct {
}

func (UnimplementedRandQuotesServer) GetQuote(context.Context, *RandQuoteRequest) (*RandQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedRandQuotesServer) ListQuotes(*ListQuotesRequest, RandQuotes_ListQuotesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListQuotes not implemented")
}
func (UnimplementedRandQuotesServer) GetSeveralCharactersQuotes(RandQuotes_GetSeveralCharactersQuotesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSeveralCharactersQuotes not implemented")
}
func (UnimplementedRandQuotesServer) QuotesChat(RandQuotes_QuotesChatServer) error {
	return status.Errorf(codes.Unimplemented, "method QuotesChat not implemented")
}
func (UnimplementedRandQuotesServer) mustEmbedUnimplementedRandQuotesServer() {}

// UnsafeRandQuotesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RandQuotesServer will
// result in compilation errors.
type UnsafeRandQuotesServer interface {
	mustEmbedUnimplementedRandQuotesServer()
}

func RegisterRandQuotesServer(s grpc.ServiceRegistrar, srv RandQuotesServer) {
	s.RegisterService(&RandQuotes_ServiceDesc, srv)
}

func _RandQuotes_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandQuotesServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RandQuotes_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandQuotesServer).GetQuote(ctx, req.(*RandQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RandQuotes_ListQuotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListQuotesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RandQuotesServer).ListQuotes(m, &randQuotesListQuotesServer{stream})
}

type RandQuotes_ListQuotesServer interface {
	Send(*ListQuotesResponse) error
	grpc.ServerStream
}

type randQuotesListQuotesServer struct {
	grpc.ServerStream
}

func (x *randQuotesListQuotesServer) Send(m *ListQuotesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _RandQuotes_GetSeveralCharactersQuotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RandQuotesServer).GetSeveralCharactersQuotes(&randQuotesGetSeveralCharactersQuotesServer{stream})
}

type RandQuotes_GetSeveralCharactersQuotesServer interface {
	SendAndClose(*SeveralCharacterQuotesResponse) error
	Recv() (*SeveralCharactersQuotesRequest, error)
	grpc.ServerStream
}

type randQuotesGetSeveralCharactersQuotesServer struct {
	grpc.ServerStream
}

func (x *randQuotesGetSeveralCharactersQuotesServer) SendAndClose(m *SeveralCharacterQuotesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *randQuotesGetSeveralCharactersQuotesServer) Recv() (*SeveralCharactersQuotesRequest, error) {
	m := new(SeveralCharactersQuotesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RandQuotes_QuotesChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RandQuotesServer).QuotesChat(&randQuotesQuotesChatServer{stream})
}

type RandQuotes_QuotesChatServer interface {
	Send(*QuotesChatResponse) error
	Recv() (*QuotesChatRequest, error)
	grpc.ServerStream
}

type randQuotesQuotesChatServer struct {
	grpc.ServerStream
}

func (x *randQuotesQuotesChatServer) Send(m *QuotesChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *randQuotesQuotesChatServer) Recv() (*QuotesChatRequest, error) {
	m := new(QuotesChatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RandQuotes_ServiceDesc is the grpc.ServiceDesc for RandQuotes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RandQuotes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.mashmorsik.rand.quote.grpc.v1.RandQuotes",
	HandlerType: (*RandQuotesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _RandQuotes_GetQuote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListQuotes",
			Handler:       _RandQuotes_ListQuotes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSeveralCharactersQuotes",
			Handler:       _RandQuotes_GetSeveralCharactersQuotes_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "QuotesChat",
			Handler:       _RandQuotes_QuotesChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rand_quote.proto",
}
